# -*- coding: utf-8 -*-
"""25exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6gLEk0i87a2O2KNWXvcYTp_XU72PtV-
"""

from openai import OpenAI

# Replace "YOUR_API_KEY" with your actual OpenAI API key
# You can find your API key at https://platform.openai.com/account/api-keys.
client = OpenAI(api_key="YOUR_API_KEY")

prompt = input("Enter your prompt: ")

response = client.responses.create(
    model="gpt-5",
    input=prompt
)

print("\nGenerated Text:")
print(response.output_text)